### ISSUE TITLE
Apply_blur() on windows 10 

### ISSUE THREAD

**Issue by mgrabka** [amrbashir/tauri-plugin-vibrancy#71] opened 2022-10-27 19:30 UTC
https://user-images.githubusercontent.com/116151164/198380692-b0f484cb-111b-499f-ba96-ffb7df161a38.mov

I think the video speaks for itself, but I'm happy to provide further context if needed.

Windows 10

**Comment by FabianLars** [comment] 2022-10-27 19:44
Duplicate of https://github.com/tauri-apps/window-vibrancy/issues/40 (upstream issue: https://github.com/tauri-apps/tauri/issues/8632)

**Closed as not planned by FabianLars** 2022-10-27 19:44 UTC

**Comment by amrbashir** [comment] 2022-10-27 20:01
did you enable transparency?
