### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by doonv** [amrbashir/tauri-plugin-vibrancy#39] opened 2022-05-13 13:48 UTC
The `README.md` doesn't explain how to implement this in a Tauri project. It just gives you some rust code but doesn't explain where and how to use it.

**Comment by FabianLars** [comment] 2022-05-13 14:29
Duplicate of #34 - More complete example in #32
Copy-paste from the PR:
```rs
use tauri::Manager;
use window_vibrancy::{apply_blur, apply_vibrancy, NSVisualEffectMaterial};

fn main() {
  tauri::Builder::default()
    .setup(|app| {
      let win = app.get_window("main").unwrap();

      #[cfg(target_os = "macos")]
      apply_vibrancy(&win, NSVisualEffectMaterial::AppearanceBased)
        .expect("Unsupported platform! 'apply_vibrancy' is only supported on macOS");

      #[cfg(target_os = "windows")]
      apply_blur(&win, Some((18, 18, 18, 125)))
        .expect("Unsupported platform! 'apply_blur' is only supported on Windows");

      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

**Closed as completed by FabianLars** 2022-05-13 14:29 UTC

**Comment by doonv** [comment] 2022-05-13 17:02
> Duplicate of #34 - More complete example in #32 Copy-paste from the PR:
> 
> ```rust
> use tauri::Manager;
> use window_vibrancy::{apply_blur, apply_vibrancy, NSVisualEffectMaterial};
> 
> fn main() {
>   tauri::Builder::default()
>     .setup(|app| {
>       let win = app.get_window("main").unwrap();
> 
>       #[cfg(target_os = "macos")]
>       apply_vibrancy(&win, NSVisualEffectMaterial::AppearanceBased)
>         .expect("Unsupported platform! 'apply_vibrancy' is only supported on macOS");
> 
>       #[cfg(target_os = "windows")]
>       apply_blur(&win, Some((18, 18, 18, 125)))
>         .expect("Unsupported platform! 'apply_blur' is only supported on Windows");
> 
>       Ok(())
>     })
>     .run(tauri::generate_context!())
>     .expect("error while running tauri application");
> }
> ```

Doesnt work, I got this error:
```
error[E0425]: cannot find value `window` in this scope      
  --> src\main.rs:19:19
   |
19 |       apply_blur(&window, Some((18, 18, 18, 125)))
   |                   ^^^^^^ not found in this scope
```

**Comment by lucasfernog** [comment] 2022-05-13 17:03
You gotta add this before that line: `let window = app.get_window("main").unwrap();` @Dan-Gamin

**Comment by PacifiK2460** [comment] 2022-07-23 15:11
While doing this with the default Vite + Electron example, neither blur nor mica effect were visible, is there something else I need to change, html / css?

**Comment by FabianLars** [comment] 2022-07-28 11:17
@PacifiK2460 I figure `Electron` is a typo right?
Anyway, you need to
1) enable [transparency](https://tauri.app/v1/api/config#windowconfig.transparent) for the window, on macOS you also need to enable [private apis](https://tauri.app/v1/api/config#tauriconfig.macosprivateapi) for transparency to work.
2) Make your html elements transparent via css. Helping with this is a little tricky, but it shouldn't be too hard. You could also try `* { background: transparent; }` (this will make every element's background transparent) first to make sure the other settings are correct.
